num_workers:  4
batch_size:  8
steps: 100_000
eval_freq: 20_000
log_freq: 200

save_checkpoint: True
save_freq: 20_000

use_policy_training_preset: True
# optimizer: OptimizerConfig | None = None
# scheduler: LRSchedulerConfig | None = None


# checkpoint_path: Path | None = field(init=False, default=None)
resume: False
job_name: "act_xarm_plate_pinch"
output_dir: "outputs/train/act_xarm_plate_pinch"


dataset:
  repo_id="Armstrong-Couch/xarm_plate_pinch"


policy:
  type: act
  device: cuda
  repo_id: "Armstrong-Couch/act_xarm_plate_pinch"


wandb:
  enable: true


